spring.application.name=employee-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/employeedb
spring.datasource.username=admin
scring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Just with this worked
spring.jpa.properties.hibernate.connection.url=jdbc:postgresql://localhost:5432/employeedb
spring.jpa.properties.hibernate.connection.username = admin
spring.jpa.properties.hibernate.connection.password = admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=THIS_IS_MY_JWT_SUPER_SECRET_01_2025
jwt.expiration=3600000